### ISSUE TITLE
Security alerts

### ISSUE THREAD

**Issue by johnjohndoe** [OpenTechSchool/social-coding#16]
Security alerts for the libraries used in this project are automatically [picked up by GitHub](https://github.com/OpenTechSchool/social-coding/network/alerts) and distributed to contributors via email.

![alerts](https://user-images.githubusercontent.com/144518/48859172-a9e8ac80-edbd-11e8-822a-a5f10dd6ce53.png)

Since this is not an in-production production project I hereby vote to **disable** security alerts at all for this particular project.

**Comment by johnjohndoe** [comment]
:up:

**Comment by mamhoff** [comment]
Disabled. Thank you!
