### ISSUE TITLE
social coding licence

### ISSUE THREAD

**Issue by nekopanic** [OpenTechSchool/social-coding#5]
Hey all,

I know this is a little odd, but I'd like to finally put a proper licence on this coursework. There was a poll conducted a while ago and Creative Commons Attribution Share-Alike was by far the most popular, so I would like to apply that. As I authored 16,412 lines out of 18,113 in the repository I think I can probably just apply it next week.

If you would like to object to the licence being applied then please comment here or let me know. We can always back out your contributions if you wish.

Otherwise, I'll apply the licence in the next week.

/cc all contributors @benoitbleuze @funkybrain @johnjohndoe @skade

**Comment by skade** [comment]
Go ahead, the license is a good choice.

**Comment by johnjohndoe** [comment]
I am fine with that
Cheers, tp

**Comment by nekopanic** [comment]
Done.
